[package]
name = "cdumay_result"
version = "0.1.0"
authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cdumay/cdumay-result-rs"
homepage =  "https://github.com/cdumay/cdumay-result-rs"
description = """
A library to serialize and deserialize result using JSON
"""

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.4", features = ["serde", "v4"] }