[package]
name = "cdumay_result"
version = "0.1.4"
authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cdumay/cdumay-result-rs"
homepage =  "https://github.com/cdumay/cdumay-result-rs"
description = """
A library to serialize and deserialize result using serde
"""

[features]
all = []
cdumay-error = ["cdumay_error"]

[dependencies]
cdumay_error = { git = "https://github.com/cdumay/cdumay-errors-rs" , optional = true }
serde = "1.0"
serde-value = "0.5"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4", "serde"] }
