[package]
name = "cdumay_result"
version = "0.1.5"
authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/cdumay_result"
repository = "https://github.com/cdumay/rust-cdumay_result"
homepage =  "https://github.com/cdumay/rust-cdumay_result"
description = """A library to serialize and deserialize result using serde"""
keywords = ["Error", "serde", "Result"]
categories = ["caching", "data-structures", "encoding"]

[badges]
gitlab = { repository = "cdumay/rust-cdumay_result" }
travis-ci = { repository = "cdumay/rust-cdumay_result" }
maintenance = { status = "as-is" }

[dependencies]
cdumay_error = { git = "https://github.com/cdumay/rust-cdumay_errors" }
serde = "1.0"
serde-value = "0.6"
serde_derive = "1.0"
uuid = { version = "0.6", features = ["v4", "serde"] }
